/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BikesBikeIdRouteImport } from './routes/bikes/$bikeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BikesBikeIdRoute = BikesBikeIdRouteImport.update({
  id: '/bikes/$bikeId',
  path: '/bikes/$bikeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bikes/$bikeId': typeof BikesBikeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bikes/$bikeId': typeof BikesBikeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bikes/$bikeId': typeof BikesBikeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bikes/$bikeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bikes/$bikeId'
  id: '__root__' | '/' | '/bikes/$bikeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BikesBikeIdRoute: typeof BikesBikeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikes/$bikeId': {
      id: '/bikes/$bikeId'
      path: '/bikes/$bikeId'
      fullPath: '/bikes/$bikeId'
      preLoaderRoute: typeof BikesBikeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BikesBikeIdRoute: BikesBikeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
